### ISSUE TITLE
bug in superstream_consumer

### ISSUE THREAD

**Issue by DanielePalaia** [qweeze/rstream#102]
After a while consumer fails:

```
Traceback (most recent call last):
  File "/Users/dpalaia/projects/rabbitmq-stream-mixing/python/python_rstream/consumer.py", line 35, in <module>
    asyncio.run(consume())
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/dpalaia/projects/rabbitmq-stream-mixing/python/python_rstream/consumer.py", line 31, in consume
    await consumer.subscribe(callback=on_message, decoder=amqp_decoder, offset_specification=offset_specification)
  File "/Users/dpalaia/projects/rabbitmq-stream-mixing/python/venv/lib/python3.11/site-packages/rstream/superstream_consumer.py", line 143, in subscribe
    consumer = await self._create_consumer()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpalaia/projects/rabbitmq-stream-mixing/python/venv/lib/python3.11/site-packages/rstream/superstream_consumer.py", line 176, in _create_consumer
    await consumer.start()
  File "/Users/dpalaia/projects/rabbitmq-stream-mixing/python/venv/lib/python3.11/site-packages/rstream/consumer.py", line 110, in start
    self._default_client = await self._pool.get(connection_closed_handler=self._connection_closed_handler)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpalaia/projects/rabbitmq-stream-mixing/python/venv/lib/python3.11/site-packages/rstream/client.py", line 566, in get
    self._clients[desired_addr] = await self.new(
                                  ^^^^^^^^^^^^^^^
  File "/Users/dpalaia/projects/rabbitmq-stream-mixing/python/venv/lib/python3.11/site-packages/rstream/client.py", line 610, in new
    await client.start()
  File "/Users/dpalaia/projects/rabbitmq-stream-mixing/python/venv/lib/python3.11/site-packages/rstream/client.py", line 170, in start
    await self._conn.open()
  File "/Users/dpalaia/projects/rabbitmq-stream-mixing/python/venv/lib/python3.11/site-packages/rstream/connection.py", line 42, in open
    raise ConnectionError(f"Could not connect to {self.host}:{self.port}")
ConnectionError: Could not connect to localhost:5552
make: *** [consumer] Error 1

```

**Comment by Gsantomaggio** [comment]
The issue seems to be solved by increasing the `CONNECT_TIMEOUT` to `3` / `5`. That makes sense since `one` second could not be enough.
