### ISSUE TITLE
Stream already exists error

### ISSUE THREAD

**Issue by wrobell** [qweeze/rstream#6]
I am using the publisher example from the readme file.

First run
```
Traceback (most recent call last):
  File "/home/wrobell/projects/snippets/rabbitmq/rabbitmq.py", line 11, in <module>
    asyncio.run(publish())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/wrobell/projects/snippets/rabbitmq/rabbitmq.py", line 9, in publish
    await producer.publish('mystream', f'msg: {i}'.encode())
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/producer.py", line 194, in publish
    publishing_ids = await self.publish_batch(
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/producer.py", line 156, in publish_batch
    publisher = await self._get_or_create_publisher(stream, publisher_name)
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/producer.py", line 110, in _get_or_create_publisher
    client = await self._get_or_create_client(stream)
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/producer.py", line 94, in _get_or_create_client
    self._clients[stream] = await self._pool.get((leader.host, leader.port))
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/client.py", line 481, in get
    self._clients[addr] = await self.new(addr)
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/client.py", line 495, in new
    await client.authenticate(
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/client.py", line 265, in authenticate
    await self.sync_request(
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/client.py", line 127, in sync_request
    resp.check_response_code()
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/schema.py", line 35, in check_response_code
    raise ServerError.from_code(code)
rstream.exceptions.SASLAuthenticationFailureLoopback
```
Please note that above error happens, when publishing a message to the stream. The related queue got created:

```
# rabbitmqctl list_queues
Timeout: 60.0 seconds ...
Listing queues for vhost / ...
name    messages
mystream        0
```
I can publish a message to the queue using Pika. Not sure, if it is configuration issue on my side...

Anyway, trying again to run the same publisher example
```
Traceback (most recent call last):
  File "/home/wrobell/projects/snippets/rabbitmq/rabbitmq.py", line 11, in <module>
    asyncio.run(publish())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/wrobell/projects/snippets/rabbitmq/rabbitmq.py", line 6, in publish
    await producer.create_stream('mystream')
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/producer.py", line 228, in create_stream
    await self.default_client.create_stream(stream, arguments)
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/client.py", line 292, in create_stream
    await self.sync_request(
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/client.py", line 127, in sync_request
    resp.check_response_code()
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/schema.py", line 35, in check_response_code
    raise ServerError.from_code(code)
rstream.exceptions.StreamAlreadyExists
```
I would expect the stream to be reused when calling `Producer.create_stream`.

**Comment by Gsantomaggio** [comment]
I think we can close this issue. 
using:
```python 
producer.create_stream('mystream', exists_ok=True)
```

It works
