### ISSUE TITLE
Cannot read messages using the examples from readme file

### ISSUE THREAD

**Issue by wrobell** [qweeze/rstream#7]
To replicate run the producer from the readme file to create stream and publish messages

```
$ rabbitmqctl list_queues
Timeout: 60.0 seconds ...
Listing queues for vhost / ...
name    messages
mystream        100
```

Then run consumer from the readme file. I am getting a lot of errors
```
Error while running handler functools.partial(<bound method Consumer._on_deliver of <rstream.consumer.Consumer object at 0x7fc27868c250>>, subscriber=_Subscriber(stream='mystream', subscription_id=1, reference='mystream_subscriber_1', client=<rstream.client.Client object at 0x7fc278697a00>, callback=<function consume.<locals>.on_message at 0x7fc277cb3e50>, decoder=<function amqp_decoder at 0x7fc2780b71f0>, offset_type=<OffsetType.FIRST: 1>, offset=0)) of frame Deliver(subscription_id=1, magic_version=80, chunk_type=0, num_entries=1, num_records=1, timestamp=1634293745617, epoch=1, chunk_first_offset=99, chunk_crc=3688700533, data_length=11, trailer_length=30, _reserved=0, data=b'\x00\x00\x00\x07msg: 99')
Traceback (most recent call last):
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/client.py", line 157, in _listener
    await maybe_coro
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/consumer.py", line 228, in _on_deliver
    maybe_coro = subscriber.callback(subscriber.decoder(message))
  File "/home/wrobell/.local/lib/python3.9/site-packages/rstream/amqp.py", line 26, in amqp_decoder
    message.decode(data)
  File "/home/wrobell/.local/lib/python3.9/site-packages/proton/_message.py", line 499, in decode
    self._check(pn_message_decode(self._msg, data))
  File "/home/wrobell/.local/lib/python3.9/site-packages/proton/_message.py", line 80, in _check
    raise exc("[%s]: %s" % (err, pn_error_text(pn_message_error(self._msg))))
proton._exceptions.MessageException: [-6]: data error: (null)
```

I am using RabbitMQ 3.9.7, rstream 0.3.0.

**Comment by wrobell** [comment]
Actually, the example I was using was from PyPI:

```
await producer.publish('mystream', f'msg: {i}'.encode())
```

If replace above line with
```
msg = AMQPMessage(body='hello: {}'.format(i))
await producer.publish('mystream', msg)
```

Looking at the changelog, the example was changed with message `change the example to AMQP 1.0`.

IMHO, it would be great to keep the first version of API as it is simpler.

Selection of protocol version probably shall be done differently, i.e. when creating producer.

**Comment by Gsantomaggio** [comment]
>raw bytes (is that AMQP 0-9-1?)

No, you can store what you want. In general we decided to use amqp 1.0 to save the messages in this way all the clients are compatible. 

But if you want you could use something else to save the messages. 

Currently, all the stream clients support amqp 1.0 as default
