### ISSUE TITLE
To review deduplication

### ISSUE THREAD

**Issue by DanielePalaia** [qweeze/rstream#99]
This issue just to carefully review/test how deduplication is working.

To see how publisher_name /message_id are manage and if everything's working fine with it.

There are actually some tests using RawMessage using different/same message_id. 
To see with different publisher_name as well

**Comment by DanielePalaia** [comment]
At the moment specifying different publisher_name generates an exception:

```
venv/bin/python3 python_rstream/producer.py
Exception in callback Producer._timer_completed(<Task finishe...ertionError()>)
handle: <Handle Producer._timer_completed(<Task finishe...ertionError()>)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/dpalaia/projects/rabbitmq-stream-mixing/python/venv/lib/python3.11/site-packages/rstream/producer.py", line 327, in _timer_completed
    raise context.exception()
  File "/Users/dpalaia/projects/rabbitmq-stream-mixing/python/venv/lib/python3.11/site-packages/rstream/producer.py", line 389, in _timer
    await self._publish_buffered_messages(stream)
  File "/Users/dpalaia/projects/rabbitmq-stream-mixing/python/venv/lib/python3.11/site-packages/rstream/producer.py", line 395, in _publish_buffered_messages
    await self._send_batch(stream, self._buffered_messages[stream], sync=False)
  File "/Users/dpalaia/projects/rabbitmq-stream-mixing/python/venv/lib/python3.11/site-packages/rstream/producer.py", line 233, in _send_batch
    publisher = await self._get_or_create_publisher(stream, publisher_name=item.publisher_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpalaia/projects/rabbitmq-stream-mixing/python/venv/lib/python3.11/site-packages/rstream/producer.py", line 161, in _get_or_create_publisher
    assert publisher.reference == publisher_name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by DanielePalaia** [comment]
Double checking with @Gsantomaggio it seems like to be a correct behaviour. 
Added example and doc here: https://github.com/qweeze/rstream/pull/98
I will close it for now
